"""
MC-Agent-Kit Skills 模块

提供 AI Agent 的技能扩展接口。
"""

from __future__ import annotations
from .base import (
    BaseSkill,
    SkillCategory,
    SkillMetadata,
    SkillPriority,
    SkillRegistry,
    SkillResult,
    get_registry,
    get_skill,
    register_skill,
)
from .modsdk import (
    ModSDKAPISearchSkill,
    ModSDKCodeGenSkill,
    ModSDKDebugSkill,
    ModSDKEventSearchSkill,
)
from .ai_enhanced import (
    CodeContextAnalyzer,
    CodeContextInfo,
    ConversationContext,
    ConversationManager,
    ConversationMessage,
    ConversationRole,
    IntentRecognitionResult,
    IntentRecognizer,
    IntentType,
    SmartRecommender,
    create_code_analyzer,
    create_conversation_manager,
    create_smart_recommender,
    get_code_analyzer,
    get_conversation_manager,
    get_smart_recommender,
)
from .intelligent_codegen import (
    CodeQualityLevel,
    CodeStyle,
    CodeTemplate,
    GeneratedCode,
    GenerationStrategy,
    IntelligentCodeGenerator,
    QualityAssessment,
    StyleCheckResult,
    generate_code,
    get_code_generator,
)
from .intelligent_fix import (
    ErrorAnalysis,
    ErrorCategory,
    ErrorPattern,
    ErrorPatternLearner,
    FixConfidence,
    FixResult,
    FixStatus,
    FixSuggestion,
    IntelligentFixer,
    analyze_and_fix,
    get_intelligent_fixer,
)
from .test_generator import (
    CoverageLevel,
    IntelligentTestGenerator,
    TestCase,
    TestReport,
    TestResult,
    TestStatus,
    TestSuite,
    TestType,
    generate_tests,
    get_test_analyzer,
    get_test_generator,
)
from .smart_generation import (
    CodeQualityLevel as SmartCodeQualityLevel,
    CodeStyle as SmartCodeStyle,
    CodeTemplate as SmartCodeTemplate,
    GeneratedCode as SmartGeneratedCode,
    GenerationStrategy as SmartGenerationStrategy,
    LLMConfig,
    LLMProvider,
    QualityAssessment as SmartQualityAssessment,
    SmartCodeGenerator,
    StyleCheckResult as SmartStyleCheckResult,
    generate_code as smart_generate_code,
    get_smart_generator,
)
from .smart_conversation import (
    ConversationContext as SmartConversationContext,
    ConversationMemory,
    ConversationMessage as SmartConversationMessage,
    ConversationRole as SmartConversationRole,
    ConversationState,
    ConversationSummary,
    IntentRecognitionResult as SmartIntentRecognitionResult,
    IntentRecognizer as SmartIntentRecognizer,
    IntentType as SmartIntentType,
    SmartConversationManager,
    TopicCategory,
    TopicTracker,
    create_session,
    get_conversation_manager as get_smart_conversation_manager,
    process_message,
)

# Iteration #50: LLM Integration
from .llm_integration import (
    AzureOpenAIClient,
    BaseLLMClient,
    ChatMessage,
    CostTracker,
    LLMClientFactory,
    LLMConfig as IntegrationLLMConfig,
    LLMProvider as IntegrationLLMProvider,
    LLMResponse,
    LLMService,
    LMStudioClient,
    MessageRole,
    MockLLMClient,
    OllamaClient,
    OpenAIClient,
    StreamChunk,
    TokenUsage,
    chat,
    get_llm_service,
)

# Iteration #50: Prompt Engineering
from .prompt_engineering import (
    ChainOfThoughtConfig,
    ChainOfThoughtPrompter,
    FewShotConfig,
    FewShotExample,
    FewShotLearner,
    PromptEngineeringService,
    PromptOptimizer,
    PromptOptimizationResult,
    PromptTemplate,
    PromptTemplateRegistry,
    PromptTemplateType,
    ReasoningType,
    build_cot_prompt,
    get_prompt_service,
    render_prompt,
)

# Iteration #50: Async Generation
from .async_generation import (
    AsyncCodeGenerator,
    AsyncGenerationResult,
    BatchGenerationConfig,
    BatchGenerationResult,
    IncrementalCache,
    LazyLoader,
    MemoryOptimizedGenerator,
    generate_code_async,
    generate_codes_batch_async,
    get_async_generator,
    get_memory_optimized_generator,
)

# Iteration #54: Knowledge Graph
from .knowledge_graph import (
    GraphEdge,
    GraphNode,
    GraphPath,
    GraphStats,
    KnowledgeGraph,
    KnowledgeGraphBuilder,
    NodeType,
    RelationStrength,
    RelationType,
    get_graph_builder,
    get_knowledge_graph,
)

# Iteration #54: Inference Engine
from .inference_engine import (
    CausalChain,
    CausalInferenceEngine,
    GraphInferenceEngine,
    InferenceContext,
    InferenceEngine,
    InferenceResult,
    InferenceStatus,
    InferenceRule,
    InferenceType,
    RuleEngine,
    RuleType,
    get_inference_engine,
    infer,
    infer_api_relations,
)

# Iteration #54: Context Enhancement
from .context_enhancement import (
    CompressionResult,
    CompressionStrategy,
    ContextCompressor,
    ContextEnhancer,
    ContextEntry,
    ContextManager,
    ContextPriority,
    ContextType,
    ContextWindow,
    KeyInfo,
    KeyInfoExtractor,
    add_context,
    get_context_enhancer,
)

# Iteration #54: Smart Completion
from .smart_completion import (
    APICompletionProvider,
    CompletionContext,
    CompletionItem,
    CompletionResult,
    CompletionSource,
    CompletionStats,
    CompletionType,
    EventCompletionProvider,
    SmartCompletionEngine,
    SnippetCompletionProvider,
    complete,
    get_completion_engine,
)

# Iteration #55: Continuous Learning
from .continuous_learning import (
    ContinuousLearner,
    ExtractionResult,
    KnowledgeSource,
    KnowledgeStatus,
    KnowledgeType,
    KnowledgeValidator,
    LearnedKnowledge,
    KnowledgeVersion,
    VerificationResult,
    extract_knowledge,
    get_continuous_learner,
    get_learned_knowledge,
)

# Iteration #55: Feedback Optimizer
from .feedback_optimizer import (
    AdjustmentScore,
    ErrorPattern as FeedbackErrorPattern,
    Feedback,
    FeedbackCollector,
    FeedbackOptimizer,
    FeedbackTarget,
    FeedbackType,
    OptimizationStats,
    get_feedback_collector,
    get_feedback_optimizer,
    optimize_items,
    record_feedback,
)

# Iteration #55: Knowledge Maintenance
from .knowledge_maintenance import (
    DuplicateGroup,
    HealthLevel,
    HealthMetrics,
    KnowledgeItem,
    KnowledgeMaintenance,
    MaintenanceAction,
    MaintenanceReport,
    OutdatedResult,
    RelationUpdate,
    get_health_report,
    get_knowledge_maintenance,
    run_maintenance,
)

# Iteration #55: Personalization
from .personalization import (
    PatternFrequency,
    PatternLearner,
    PersonalizationEngine,
    PersonalizationResult,
    PersonalizationStats,
    PreferenceManager,
    PreferenceType,
    ProjectContext,
    ProjectContextManager,
    SessionMemory,
    UsagePattern,
    UserPreference,
    adapt_suggestion,
    get_common_patterns,
    get_personalization_engine,
    record_preference,
)

__all__ = [
    # 基类和工具
    "BaseSkill",
    "SkillCategory",
    "SkillMetadata",
    "SkillPriority",
    "SkillRegistry",
    "SkillResult",
    "get_registry",
    "get_skill",
    "register_skill",
    # ModSDK Skills
    "ModSDKAPISearchSkill",
    "ModSDKCodeGenSkill",
    "ModSDKDebugSkill",
    "ModSDKEventSearchSkill",
    # AI Enhanced
    "CodeContextAnalyzer",
    "CodeContextInfo",
    "ConversationContext",
    "ConversationManager",
    "ConversationMessage",
    "ConversationRole",
    "IntentRecognitionResult",
    "IntentRecognizer",
    "IntentType",
    "SmartRecommender",
    "create_code_analyzer",
    "create_conversation_manager",
    "create_smart_recommender",
    "get_code_analyzer",
    "get_conversation_manager",
    "get_smart_recommender",
    # Intelligent Code Generation
    "CodeQualityLevel",
    "CodeStyle",
    "CodeTemplate",
    "GeneratedCode",
    "GenerationStrategy",
    "IntelligentCodeGenerator",
    "QualityAssessment",
    "StyleCheckResult",
    "generate_code",
    "get_code_generator",
    # Intelligent Fix
    "ErrorAnalysis",
    "ErrorCategory",
    "ErrorPattern",
    "ErrorPatternLearner",
    "FixConfidence",
    "FixResult",
    "FixStatus",
    "FixSuggestion",
    "IntelligentFixer",
    "analyze_and_fix",
    "get_intelligent_fixer",
    # Test Generator
    "CoverageLevel",
    "IntelligentTestGenerator",
    "TestCase",
    "TestReport",
    "TestResult",
    "TestStatus",
    "TestSuite",
    "TestType",
    "generate_tests",
    "get_test_analyzer",
    "get_test_generator",
    # Smart Generation (Iteration #49)
    "SmartCodeGenerator",
    "SmartCodeQualityLevel",
    "SmartCodeStyle",
    "SmartCodeTemplate",
    "SmartGeneratedCode",
    "SmartGenerationStrategy",
    "LLMConfig",
    "LLMProvider",
    "SmartQualityAssessment",
    "SmartStyleCheckResult",
    "smart_generate_code",
    "get_smart_generator",
    # Smart Conversation (Iteration #49)
    "SmartConversationManager",
    "SmartConversationContext",
    "SmartConversationMessage",
    "SmartConversationRole",
    "ConversationMemory",
    "ConversationState",
    "ConversationSummary",
    "SmartIntentRecognitionResult",
    "SmartIntentRecognizer",
    "SmartIntentType",
    "TopicCategory",
    "TopicTracker",
    "create_session",
    "get_smart_conversation_manager",
    "process_message",
    # LLM Integration (Iteration #50)
    "BaseLLMClient",
    "OpenAIClient",
    "AzureOpenAIClient",
    "OllamaClient",
    "LMStudioClient",
    "MockLLMClient",
    "LLMClientFactory",
    "LLMService",
    "ChatMessage",
    "MessageRole",
    "TokenUsage",
    "CostTracker",
    "LLMResponse",
    "StreamChunk",
    "IntegrationLLMConfig",
    "IntegrationLLMProvider",
    "get_llm_service",
    "chat",
    # Prompt Engineering (Iteration #50)
    "PromptTemplateRegistry",
    "PromptTemplate",
    "PromptTemplateType",
    "FewShotExample",
    "FewShotConfig",
    "FewShotLearner",
    "ChainOfThoughtPrompter",
    "ChainOfThoughtConfig",
    "ReasoningType",
    "PromptOptimizer",
    "PromptOptimizationResult",
    "PromptEngineeringService",
    "get_prompt_service",
    "render_prompt",
    "build_cot_prompt",
    # Async Generation (Iteration #50)
    "AsyncCodeGenerator",
    "AsyncGenerationResult",
    "BatchGenerationConfig",
    "BatchGenerationResult",
    "IncrementalCache",
    "LazyLoader",
    "MemoryOptimizedGenerator",
    "get_async_generator",
    "get_memory_optimized_generator",
    "generate_code_async",
    "generate_codes_batch_async",
    # Knowledge Graph (Iteration #54)
    "KnowledgeGraph",
    "GraphEdge",
    "GraphNode",
    "GraphPath",
    "GraphStats",
    "NodeType",
    "RelationType",
    "RelationStrength",
    "KnowledgeGraphBuilder",
    "get_knowledge_graph",
    "get_graph_builder",
    # Inference Engine (Iteration #54)
    "InferenceEngine",
    "InferenceRule",
    "InferenceResult",
    "InferenceType",
    "InferenceStatus",
    "InferenceContext",
    "RuleType",
    "CausalChain",
    "RuleEngine",
    "GraphInferenceEngine",
    "CausalInferenceEngine",
    "get_inference_engine",
    "infer",
    "infer_api_relations",
    # Context Enhancement (Iteration #54)
    "ContextManager",
    "ContextEntry",
    "ContextWindow",
    "ContextPriority",
    "ContextType",
    "CompressionStrategy",
    "CompressionResult",
    "KeyInfo",
    "ContextCompressor",
    "KeyInfoExtractor",
    "ContextEnhancer",
    "get_context_enhancer",
    "add_context",
    # Smart Completion (Iteration #54)
    "SmartCompletionEngine",
    "CompletionItem",
    "CompletionContext",
    "CompletionResult",
    "CompletionType",
    "CompletionSource",
    "CompletionStats",
    "APICompletionProvider",
    "EventCompletionProvider",
    "SnippetCompletionProvider",
    "get_completion_engine",
    "complete",
    # Continuous Learning (Iteration #55)
    "ContinuousLearner",
    "ExtractionResult",
    "KnowledgeSource",
    "KnowledgeStatus",
    "KnowledgeType",
    "KnowledgeValidator",
    "LearnedKnowledge",
    "KnowledgeVersion",
    "VerificationResult",
    "extract_knowledge",
    "get_continuous_learner",
    "get_learned_knowledge",
    # Feedback Optimizer (Iteration #55)
    "AdjustmentScore",
    "FeedbackErrorPattern",
    "Feedback",
    "FeedbackCollector",
    "FeedbackOptimizer",
    "FeedbackTarget",
    "FeedbackType",
    "OptimizationStats",
    "get_feedback_collector",
    "get_feedback_optimizer",
    "optimize_items",
    "record_feedback",
    # Knowledge Maintenance (Iteration #55)
    "DuplicateGroup",
    "HealthLevel",
    "HealthMetrics",
    "KnowledgeItem",
    "KnowledgeMaintenance",
    "MaintenanceAction",
    "MaintenanceReport",
    "OutdatedResult",
    "RelationUpdate",
    "get_health_report",
    "get_knowledge_maintenance",
    "run_maintenance",
    # Personalization (Iteration #55)
    "PatternFrequency",
    "PatternLearner",
    "PersonalizationEngine",
    "PersonalizationResult",
    "PersonalizationStats",
    "PreferenceManager",
    "PreferenceType",
    "ProjectContext",
    "ProjectContextManager",
    "SessionMemory",
    "UsagePattern",
    "UserPreference",
    "adapt_suggestion",
    "get_common_patterns",
    "get_personalization_engine",
    "record_preference",
]


def register_modsdk_skills(kb_path: str | None = None) -> None:
    """注册所有 ModSDK Skills

    Args:
        kb_path: 可选的知识库文件路径
    """
    registry = get_registry()

    # 注册 API 搜索 Skill
    api_skill = ModSDKAPISearchSkill(kb_path=kb_path)
    registry.register(api_skill)

    # 注册事件搜索 Skill
    event_skill = ModSDKEventSearchSkill(kb_path=kb_path)
    registry.register(event_skill)

    # 注册代码生成 Skill
    code_gen_skill = ModSDKCodeGenSkill()
    registry.register(code_gen_skill)

    # 注册调试辅助 Skill
    debug_skill = ModSDKDebugSkill()
    registry.register(debug_skill)
