"""Documentation templates for MC-Agent-Kit.

This module provides templates for:
- API documentation
- User guides
- Code examples
- Best practices
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class TemplateType(Enum):
    """Types of documentation templates."""
    API_REFERENCE = "api_reference"
    USER_GUIDE = "user_guide"
    QUICK_START = "quick_start"
    BEST_PRACTICES = "best_practices"
    FAQ = "faq"
    CONTRIBUTING = "contributing"
    CHANGELOG = "changelog"
    EXAMPLE = "example"
    TUTORIAL = "tutorial"


@dataclass
class DocTemplate:
    """A documentation template."""
    name: str
    type: TemplateType
    content: str
    variables: list[str] = field(default_factory=list)
    description: str = ""
    language: str = "en"


# API Reference Template
API_REFERENCE_TEMPLATE = """# {module_name} API Reference

> Version: {version}
> Last Updated: {date}

## Overview

{description}

## Functions

{functions}

## Classes

{classes}

## Exceptions

{exceptions}

## Examples

```python
{example_code}
```

## See Also

{see_also}

---

*Generated by MC-Agent-Kit Documentation Generator*
"""

# Function Documentation Template
FUNCTION_TEMPLATE = """### `{name}`

```python
{signature}
```

{description}

**Parameters:**

| Name | Type | Default | Description |
|------|------|---------|-------------|
{parameters}

**Returns:**

`{return_type}`: {return_description}

**Raises:**

{raises}

**Examples:**

```python
{example}
```
"""

# Class Documentation Template
CLASS_TEMPLATE = """### `{name}`

```python
{signature}
```

{description}

**Attributes:**

| Name | Type | Description |
|------|------|-------------|
{attributes}

**Methods:**

{methods}

**Examples:**

```python
{example}
```
"""

# User Guide Template
USER_GUIDE_TEMPLATE = """# {title}

> Version: {version}

## Introduction

{introduction}

## Getting Started

{getting_started}

## Basic Usage

{basic_usage}

## Advanced Usage

{advanced_usage}

## Configuration

{configuration}

## Troubleshooting

{troubleshooting}

## FAQ

{faq}

## Further Reading

- [API Reference]({api_reference_link})
- [Examples](./examples/)
- [Contributing](./CONTRIBUTING.md)
"""

# Quick Start Template
QUICK_START_TEMPLATE = """# Quick Start Guide

## Installation

```bash
pip install mc-agent-kit
```

## Basic Commands

### Search API

```bash
mc-agent api "create entity"
```

### Create Project

```bash
mc-agent create project my-addon
```

### Run Addon

```bash
mc-agent run ./my-addon
```

## Next Steps

- Read the [User Guide](./USER_GUIDE.md)
- Check out [Examples](./examples/)
- Browse the [API Reference](./docs/api/)
"""

# Best Practices Template
BEST_PRACTICES_TEMPLATE = """# ModSDK Best Practices

## Code Organization

{code_organization}

### Project Structure

```
my-addon/
├── behavior_pack/
│   ├── manifest.json
│   ├── entities/
│   └── scripts/
│       └── main.py
└── resource_pack/
    ├── manifest.json
    └── textures/
```

## Performance Tips

{performance_tips}

### 1. Minimize Event Handlers

Register only necessary event handlers to reduce overhead.

```python
# Good: Register only what you need
@mod.serverEvent('OnServerChat')
def on_chat(args):
    pass

# Avoid: Registering many unused handlers
```

### 2. Use Efficient Data Structures

Choose appropriate data structures for your use case.

### 3. Cache Frequently Used Values

Store results of expensive operations.

## Error Handling

{error_handling}

### Common Patterns

```python
# Safe dictionary access
value = config.get('key', default_value)

# Try-except for risky operations
try:
    result = risky_operation()
except Exception as e:
    print(f"Error: {e}")
```

## Memory Management

{memory_management}

### Tips

1. Clean up resources when done
2. Avoid circular references
3. Use weak references where appropriate

## Testing

{testing}

### Test Structure

```python
def test_my_feature():
    # Setup
    # ...
    
    # Execute
    # ...
    
    # Assert
    # ...
```
"""

# FAQ Template
FAQ_TEMPLATE = """# Frequently Asked Questions

## General

### Q: What is MC-Agent-Kit?

A: MC-Agent-Kit is an AI-powered toolkit for Minecraft NetEase ModSDK development.

### Q: How do I install it?

A: Run `pip install mc-agent-kit` in your Python environment.

{general_questions}

## CLI Usage

### Q: How do I search for an API?

A: Use `mc-agent api <query>` to search by keywords.

### Q: How do I create a new project?

A: Use `mc-agent create project <name>` to create a new Addon project.

{cli_questions}

## Development

### Q: What Python version do I need?

A: MC-Agent-Kit requires Python 3.13+. The game uses Python 2.7.

### Q: How do I debug errors?

A: Use `mc-agent debug --file <log_file>` to analyze error logs.

{development_questions}

## Troubleshooting

### Q: Command not found?

A: Make sure MC-Agent-Kit is installed and in your PATH.

{troubleshooting_questions}
"""

# Contributing Template
CONTRIBUTING_TEMPLATE = """# Contributing to MC-Agent-Kit

Thank you for your interest in contributing!

## Development Setup

1. Clone the repository:
   ```bash
   git clone https://github.com/your-repo/MC-Agent-Kit.git
   cd MC-Agent-Kit
   ```

2. Install dependencies:
   ```bash
   pip install -e ".[dev]"
   ```

3. Run tests:
   ```bash
   pytest src/tests/
   ```

## Code Style

- Follow PEP 8
- Use type hints
- Write docstrings
- Keep functions focused

## Testing

- Write tests for new features
- Ensure all tests pass before submitting
- Aim for >85% coverage

## Pull Requests

1. Create a feature branch
2. Make your changes
3. Add tests
4. Submit a PR

## Code of Conduct

Be respectful and inclusive.
"""

# Example Template
EXAMPLE_TEMPLATE = """# Example: {title}

## Description

{description}

## Difficulty

{difficulty} (beginner/intermediate/advanced)

## Time Estimate

{time_estimate}

## Full Code

```python
{code}
```

## Explanation

{explanation}

## Output

```
{output}
```

## Variations

{variations}

## Next Steps

- Try modifying the code
- Check the [API Reference](../docs/api/{api_link})
- Explore more [Examples](./)
"""

# Tutorial Template
TUTORIAL_TEMPLATE = """# Tutorial: {title}

## Prerequisites

{prerequisites}

## Learning Objectives

By the end of this tutorial, you will:

{objectives}

## Step 1: {step1_title}

{step1_content}

## Step 2: {step2_title}

{step2_content}

## Step 3: {step3_title}

{step3_content}

## Summary

{summary}

## Next Steps

{next_steps}
"""


def get_template(template_type: TemplateType) -> DocTemplate:
    """Get a template by type.

    Args:
        template_type: Type of template

    Returns:
        DocTemplate instance
    """
    templates = {
        TemplateType.API_REFERENCE: DocTemplate(
            name="API Reference",
            type=TemplateType.API_REFERENCE,
            content=API_REFERENCE_TEMPLATE,
            variables=[
                "module_name", "version", "date", "description",
                "functions", "classes", "exceptions", "example_code",
                "see_also"
            ],
            description="Template for API documentation",
        ),
        TemplateType.USER_GUIDE: DocTemplate(
            name="User Guide",
            type=TemplateType.USER_GUIDE,
            content=USER_GUIDE_TEMPLATE,
            variables=[
                "title", "version", "introduction", "getting_started",
                "basic_usage", "advanced_usage", "configuration",
                "troubleshooting", "faq", "api_reference_link"
            ],
            description="Template for user guides",
        ),
        TemplateType.QUICK_START: DocTemplate(
            name="Quick Start",
            type=TemplateType.QUICK_START,
            content=QUICK_START_TEMPLATE,
            variables=[],
            description="Quick start guide template",
        ),
        TemplateType.BEST_PRACTICES: DocTemplate(
            name="Best Practices",
            type=TemplateType.BEST_PRACTICES,
            content=BEST_PRACTICES_TEMPLATE,
            variables=[
                "code_organization", "performance_tips", "error_handling",
                "memory_management", "testing"
            ],
            description="Template for best practices guide",
        ),
        TemplateType.FAQ: DocTemplate(
            name="FAQ",
            type=TemplateType.FAQ,
            content=FAQ_TEMPLATE,
            variables=[
                "general_questions", "cli_questions", "development_questions",
                "troubleshooting_questions"
            ],
            description="Template for FAQ document",
        ),
        TemplateType.CONTRIBUTING: DocTemplate(
            name="Contributing",
            type=TemplateType.CONTRIBUTING,
            content=CONTRIBUTING_TEMPLATE,
            variables=[],
            description="Template for contributing guide",
        ),
        TemplateType.EXAMPLE: DocTemplate(
            name="Example",
            type=TemplateType.EXAMPLE,
            content=EXAMPLE_TEMPLATE,
            variables=[
                "title", "description", "difficulty", "time_estimate",
                "code", "explanation", "output", "variations", "api_link"
            ],
            description="Template for code examples",
        ),
        TemplateType.TUTORIAL: DocTemplate(
            name="Tutorial",
            type=TemplateType.TUTORIAL,
            content=TUTORIAL_TEMPLATE,
            variables=[
                "title", "prerequisites", "objectives",
                "step1_title", "step1_content",
                "step2_title", "step2_content",
                "step3_title", "step3_content",
                "summary", "next_steps"
            ],
            description="Template for tutorials",
        ),
    }

    return templates.get(template_type, templates[TemplateType.API_REFERENCE])


def render_template(template: DocTemplate, **kwargs) -> str:
    """Render a template with variables.

    Args:
        template: DocTemplate to render
        **kwargs: Template variables

    Returns:
        Rendered content
    """
    content = template.content

    # Set defaults for missing variables
    defaults = {
        "module_name": "Module",
        "version": "1.0.0",
        "date": "",
        "description": "Description not available.",
        "functions": "No functions documented.",
        "classes": "No classes documented.",
        "exceptions": "No exceptions documented.",
        "example_code": "# Example not available",
        "see_also": "No related documentation.",
        "title": "Documentation",
        "introduction": "",
        "getting_started": "",
        "basic_usage": "",
        "advanced_usage": "",
        "configuration": "",
        "troubleshooting": "",
        "faq": "",
        "api_reference_link": "../docs/api/",
        "difficulty": "beginner",
        "time_estimate": "10 minutes",
        "code": "# Code not available",
        "explanation": "",
        "output": "",
        "variations": "",
        "api_link": "",
        "prerequisites": "",
        "objectives": "",
        "step1_title": "Getting Started",
        "step1_content": "",
        "step2_title": "Next Step",
        "step2_content": "",
        "step3_title": "Final Step",
        "step3_content": "",
        "summary": "",
        "next_steps": "",
        "general_questions": "",
        "cli_questions": "",
        "development_questions": "",
        "troubleshooting_questions": "",
        "code_organization": "",
        "performance_tips": "",
        "error_handling": "",
        "memory_management": "",
        "testing": "",
    }

    # Merge defaults with provided kwargs
    variables = {**defaults, **kwargs}

    return content.format(**variables)


def create_api_doc(
    name: str,
    module: str = "",
    description: str = "",
    parameters: list[dict[str, Any]] | None = None,
    returns: str = "",
    raises: list[str] | None = None,
    examples: list[str] | None = None,
) -> str:
    """Create API documentation for a function.

    Args:
        name: Function name
        module: Module name
        description: Function description
        parameters: List of parameter dicts
        returns: Return type description
        raises: List of exceptions
        examples: List of example code

    Returns:
        Formatted documentation string
    """
    # Build parameters table
    params_table = ""
    if parameters:
        for p in parameters:
            params_table += f"| `{p.get('name', 'N/A')}` | `{p.get('type', 'any')}` | {p.get('default', '-')} | {p.get('description', '')} |\n"
    else:
        params_table = "| None | - | - | This function has no parameters |\n"

    # Build raises section
    raises_section = ""
    if raises:
        for r in raises:
            raises_section += f"- {r}\n"
    else:
        raises_section = "None\n"

    # Build examples
    example_code = "\n".join(examples) if examples else "# No example available"

    template = get_template(TemplateType.API_REFERENCE)
    
    return render_template(
        template,
        module_name=module or name,
        description=description,
        functions=f"### `{name}`\n\n{description}",
        example_code=example_code,
    )


def create_user_guide(
    title: str,
    introduction: str,
    getting_started: str,
    basic_usage: str,
    advanced_usage: str = "",
    configuration: str = "",
    troubleshooting: str = "",
    faq: str = "",
) -> str:
    """Create a user guide document.

    Args:
        title: Guide title
        introduction: Introduction text
        getting_started: Getting started section
        basic_usage: Basic usage section
        advanced_usage: Advanced usage section
        configuration: Configuration section
        troubleshooting: Troubleshooting section
        faq: FAQ section

    Returns:
        Formatted user guide string
    """
    template = get_template(TemplateType.USER_GUIDE)
    
    return render_template(
        template,
        title=title,
        introduction=introduction,
        getting_started=getting_started,
        basic_usage=basic_usage,
        advanced_usage=advanced_usage,
        configuration=configuration,
        troubleshooting=troubleshooting,
        faq=faq,
    )


def create_example_doc(
    title: str,
    description: str,
    code: str,
    explanation: str = "",
    output: str = "",
    difficulty: str = "beginner",
    time_estimate: str = "10 minutes",
) -> str:
    """Create an example document.

    Args:
        title: Example title
        description: Example description
        code: Example code
        explanation: Code explanation
        output: Expected output
        difficulty: Difficulty level
        time_estimate: Time estimate

    Returns:
        Formatted example document
    """
    template = get_template(TemplateType.EXAMPLE)
    
    return render_template(
        template,
        title=title,
        description=description,
        code=code,
        explanation=explanation,
        output=output,
        difficulty=difficulty,
        time_estimate=time_estimate,
    )